# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  cache_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - save_cache:
          paths: [inventory]
          key: inventory_file

  restore_inventory_cache:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: inventory_file

  workspace_inventory:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/lesson4
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - inventory

  attach_inventory_workspace:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/lesson4
    steps:
      - checkout
      - attach_workspace:
          at: ~/lesson4

workflows:
  my_workflow:
    jobs:
      - cache_inventory
      - restore_inventory_cache:
          requires: [cache_inventory]
      - workspace_inventory
      - attach_inventory_workspace:
          requires: [workspace_inventory]
